steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/prisma-migration", "."]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/prisma-migration"]

  # Cloud Run Jobs Deploy
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "jobs",
        "deploy",
        "prisma-migration-job",
        "--image",
        "gcr.io/${PROJECT_ID}/prisma-migration",
        "--region",
        "asia-northeast1",
        "--execute-now",
      ]
