import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatGPT Client</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Chat GPT Client</h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h3 className={inter.className}>設定値１</h3>
            <p>
              <input type={"text"} />
            </p>
          </div>
          <div className={styles.card}>
            <h3 className={inter.className}>設定値２</h3>
            <p>
              <input type={"text"} />
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
