import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const Create: NextPage = () => {
  const title = 'Todo App Create'
  const description = '新規作成'
  const router = useRouter()

  useEffect(() => {}, [])

  const [state, setSate] = useState({ value: '' })

  const handleSubmit = (event: any) => {
    event.preventDefault()
    fetch(`/api/todos/`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ title: state.value }),
    })
      .then((res) => {
        alert('OK')
        router.push('/')
      })
      .catch((res) => {
        alert('NG')
        router.push('/')
      })
  }

  const handleChange = (e: any) => {
    setSate({ value: e.target.value })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{title}</h1>

        <p className={styles.description}>{description}</p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <p>新規作成</p>
            <form onSubmit={handleSubmit}>
              <label>
                title:
                <input type="text" value={state.value} onChange={handleChange} />
              </label>
              <input type="submit" value="OK" />
            </form>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Create
