services:
  ui:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - ui-node-modules:/workspace/node_modules
      - ui-extensions:/root/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  ui-node-modules:
  ui-extensions:
